{% materialization dynamic_table, adapter='clickzetta' %}

  {#--
    Dynamic table materialization — declarative incremental refresh.
    The system automatically tracks upstream changes (INSERT/UPDATE/DELETE)
    and incrementally refreshes the table on schedule.

    Key behaviors:
    - Schema is FIXED at creation time. If the upstream source table adds a column,
      the dynamic table will NOT automatically include it — even if the model uses
      SELECT *. To pick up schema changes, run: dbt run --full-refresh
    - refresh_interval drives automatic refresh; no Studio scheduling needed.
    - Manual refresh: REFRESH DYNAMIC TABLE <name>

    on_configuration_change:
    - continue (default): no-op when table already exists
    - apply: CREATE OR REPLACE to update refresh_interval/refresh_vc/SQL
      (ClickZetta does not support ALTER DYNAMIC TABLE for config changes)
    - fail: raise compiler error when table already exists
  --#}

  {% set existing_relation = load_cached_relation(this) %}
  {% set target_relation = this.incorporate(type=this.DynamicTable) %}

  {% set build_sql = dynamic_table_get_build_sql(existing_relation, target_relation) %}

  {% if build_sql == '' %}
      {{ dynamic_table_execute_no_op(target_relation) }}
  {% else %}
      {{ dynamic_table_execute_build_sql(build_sql, existing_relation, target_relation) }}
  {% endif %}

  {{ run_hooks(post_hooks) }}

  {{ return({'relations': [target_relation]}) }}

{% endmaterialization %}


{% macro dynamic_table_get_build_sql(existing_relation, target_relation) %}
    {#--
      Scenarios:
      1. existing_relation is none → CREATE
      2. existing_relation exists but is not a dynamic table → REPLACE (type changed)
      3. existing_relation is a dynamic table + full_refresh → depends on full_refresh_strategy
      4. on_configuration_change=apply → REPLACE (CREATE OR REPLACE updates config + SQL)
      5. on_configuration_change=fail → raise compiler error
      6. on_configuration_change=continue (default) → no-op

      full_refresh_strategy config:
      - replace (default): CREATE OR REPLACE — preserves data and grants, preferred path.
        Can fail with CZLH-42000 when the engine's incremental plan generated by OR REPLACE
        is rejected (e.g. models with OUTER/SEMI/ANTI joins). Switch to 'recreate' for those.
      - recreate: DROP + fresh CREATE — trade-off: loses grants, forces downstream dynamic
        tables to rebuild. Only use when 'replace' fails.
    --#}
    {% set full_refresh_mode = should_full_refresh() %}
    {% set on_config_change = config.get('on_configuration_change', 'continue') | lower %}
    {% set refresh_strategy = config.get('full_refresh_strategy', 'replace') | lower %}

    {% if existing_relation is none %}
        {% set build_sql = clickzetta__create_dynamic_table_as(target_relation, sql) %}
    {% elif full_refresh_mode and existing_relation.is_dynamic_table and refresh_strategy == 'recreate' %}
        {% set build_sql = clickzetta__create_dynamic_table_as(target_relation, sql) %}
    {% elif full_refresh_mode or not existing_relation.is_dynamic_table %}
        {% set build_sql = clickzetta__replace_dynamic_table_as(target_relation, sql) %}
    {% elif on_config_change == 'apply' %}
        {#-- ALTER DYNAMIC TABLE updates refresh_interval/refresh_vc without
             resetting the refresh baseline or triggering a full refresh.
             SQL changes still require --full-refresh or full_refresh_strategy. --#}
        {% set build_sql = clickzetta__alter_dynamic_table(target_relation) %}
    {% elif on_config_change == 'fail' %}
        {{ exceptions.raise_compiler_error(
            "Dynamic table '" ~ target_relation ~ "' already exists. "
            ~ "Set on_configuration_change='apply' to recreate it, or run with --full-refresh."
        ) }}
    {% else %}
        {#-- continue (default): no-op, data refreshed by schedule --#}
        {% set build_sql = '' %}
    {% endif %}

    {% do return(build_sql) %}

{% endmacro %}


{% macro dynamic_table_execute_no_op(relation) %}
    {% do store_raw_result(
        name="main",
        message="no-op — dynamic table exists and refreshes on schedule: " ~ relation,
        code="skip",
        rows_affected="-1"
    ) %}
{% endmacro %}


{% macro dynamic_table_execute_build_sql(build_sql, existing_relation, target_relation) %}

    {%- set refresh_strategy = config.get('full_refresh_strategy', 'replace') | lower -%}
    {%- set is_alter = build_sql | trim | lower | truncate(5, false, '') == 'alter' -%}

    {#--
      recreate strategy: DROP + CREATE instead of CREATE OR REPLACE.
      Used when the engine rejects the incremental plan generated by OR REPLACE.
      Trade-off: loses grants, forces downstream dynamic tables to rebuild.
    --#}
    {%- if refresh_strategy == 'recreate' and existing_relation is not none -%}
        {% call statement('drop_for_recreate') %}
            drop dynamic table if exists {{ target_relation }}
        {% endcall %}
    {%- endif %}

    {% call statement(name="main") %}
        {{ build_sql }}
    {% endcall %}

    {#--
      After CREATE or REPLACE, trigger an immediate refresh so the table is
      queryable right away. ALTER does not need a refresh — it only changes
      scheduling config without affecting the table data.
    --#}
    {%- if not is_alter -%}
    {% call statement('initialize_refresh') %}
        refresh dynamic table {{ target_relation }}
    {% endcall %}
    {%- endif %}

    {%- set grant_config = config.get('grants') -%}
    {%- set should_revoke = should_revoke(existing_relation, full_refresh_mode=True) if refresh_strategy != 'recreate' else false -%}
    {% do apply_grants(target_relation, grant_config, should_revoke=should_revoke) %}

    {% do persist_docs(target_relation, model) %}

{% endmacro %}
